apiVersion: apps/v1
kind: Deployment
metadata:
  name: donateraja-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: donateraja-frontend
  template:
    metadata:
      labels:
        app: donateraja-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          env:
            {{- range $key, $value := .Values.frontend.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/config.json
              subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: donateraja-frontend-config
