apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: donateraja-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /backend/?(.*)
            pathType: Prefix
            backend:
              service:
                name: donateraja-backend
                port:
                  number: 8080
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: donateraja-frontend
                port:
                  number: 80
    {{- end }}
